import {
  AlertTriangle,
  ArrowLeft,
  Bell,
  Bookmark,
  Bot,
  Building2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleHelp,
  CirclePlus,
  CircleX,
  CodeXml,
  CreditCard,
  DollarSign,
  Download,
  EllipsisVertical,
  Eraser,
  Eye,
  GitCompare,
  Globe,
  HandCoins,
  History,
  Inbox,
  Key,
  LayoutDashboard,
  ListFilter,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Moon,
  Pin,
  PinOff,
  Radar,
  RefreshCw,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Slash,
  Smartphone,
  SquareArrowOutUpRight,
  Store,
  Sun,
  SunMoon,
  Tag,
  ToyBrick,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  TruckElectric,
  Undo2,
  User,
  Warehouse,
  Webhook,
  X,
} from "lucide-react";

export const uiIcons = {
  mail: Mail,
  spinner: LoaderCircle,
  lock: Lock,
  dashboard: LayoutDashboard,
  settings: Settings,
  helpdesk: Inbox,
  help: CircleHelp,
  more: EllipsisVertical,
  add: CirclePlus,
  left: ChevronLeft,
  right: ChevronRight,
  doubleLeft: ChevronsLeft,
  doubleRight: ChevronsRight,
  delete: Trash2,
  tab: Bookmark,
  filter: ListFilter,
  search: Search,
  down: ChevronDown,
  dark: Moon,
  light: Sun,
  system: SunMoon,
  sync: RefreshCw,
  view: Eye,
  template: ScrollText,
  listing: Tag,
  marketplace: Store,
  stock: Warehouse,
  product: ToyBrick,
  order: ShoppingCart,
  arrowLeft: ArrowLeft,
  logOut: LogOut,
  success: Check,
  error: CircleX,
  externalLink: SquareArrowOutUpRight,
  redeem: TruckElectric,
  download: Download,
  pin: Pin,
  unpin: PinOff,
  close: X,
  history: History,
  clear: Eraser,
  rising: TrendingUp,
  declining: TrendingDown,
  alert: AlertTriangle,
  user: User,
  organization: Building2,
  security: Shield,
  notification: Bell,
  billing: CreditCard,
  smartphone: Smartphone,
  globe: Globe,
  password: Key,
  shipping: Truck,
  ai: Bot,
  return: Undo2,
  radar: Radar,
  code: CodeXml,
  privacy: ShieldCheck,
  store: Store,
  api: Webhook,
  refund: HandCoins,
  slash: Slash,
  money: DollarSign,
  connect: GitCompare,
  check: Check,
  issue: CircleAlert,
};
