/**
 * Retry low-confidence mappings using Pass 2 synonym expansion.
 *
 * Reads low-confidence.json (generated by extract-low-confidence.ts),
 * applies AI synonym expansion + local token filtering + AI re-mapping,
 * then patches the per-category mapping files in place.
 *
 * Usage:
 *   bun run packages/taxonomy/scripts/retry-low-confidence.ts
 *
 * Options:
 *   --max-targets <n>   Max Shopify targets per batch (default: 200)
 *   --category <name>   Only retry entries from this eBay category
 *   --dry-run           Show what would be retried without calling AI
 *
 * Input:  data/integrations/ebay/{version}/mappings/low-confidence.json
 * Output: Updates data/integrations/ebay/{version}/mappings/categories/*.json
 *         Regenerates data/integrations/ebay/{version}/mappings/mappings.json
 */

import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import dotenv from "dotenv";
import OpenAI from "openai";

dotenv.config({ path: resolve(import.meta.dirname, ".env") });

const DATA_DIR = join(import.meta.dir, "../data");
const SHOPIFY_DIR = join(DATA_DIR, "categories");
const EBAY_INTEGRATIONS_DIR = join(DATA_DIR, "integrations/ebay");
const BATCH_SIZE = 100;
const DEFAULT_MAX_TARGETS = 200;
const MODEL = "gpt-4.1-mini";
const JSON_ARRAY_RE = /\[[\s\S]*\]/;
const TOKENIZE_RE = /[\s>,.&/()[\]\-–—]+/;

// Categories matching these patterns are auto-marked uncategorized (no AI needed)
const EXCLUDED_PATTERNS = [
  "test category",
  "internal use",
  "ebay use only",
  "blocked category",
];

function isExcludedCategory(fullName: string): boolean {
  const lower = fullName.toLowerCase();
  return EXCLUDED_PATTERNS.some((pattern) => lower.includes(pattern));
}

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

interface ReviewEntry {
  confidence: number;
  ebayCategory: string;
  ebayFullName: string;
  ebayId: string;
  reason: string;
  shopifyCategoryId: string;
  shopifyFullName: string;
}

interface MappingEntry {
  confidence: number;
  ebayFullName: string;
  ebayId: string;
  mappingSource: string;
  shopifyCategoryId: string;
  shopifyFullName: string;
}

interface CategoryFile {
  ebayCategory: string;
  highConfidence: number;
  lowConfidence: number;
  mappings: MappingEntry[];
  totalMapped: number;
}

interface ShopifyCategory {
  children: { id: string; name: string }[];
  full_name: string;
  id: string;
  level: number;
  name: string;
  parent_id: string | null;
}

// ---------------------------------------------------------------------------
// SHOPIFY_FILES
// ---------------------------------------------------------------------------

const SHOPIFY_FILES: Record<string, string> = {
  aa: "aa_apparel_and_accessories.json",
  ae: "ae_arts_and_entertainment.json",
  ap: "ap_animals_and_pet_supplies.json",
  bi: "bi_business_and_industrial.json",
  bt: "bt_baby_and_toddler.json",
  bu: "bu_bundles.json",
  co: "co_cameras_and_optics.json",
  el: "el_electronics.json",
  fb: "fb_food_beverages_and_tobacco.json",
  fr: "fr_furniture.json",
  gc: "gc_gift_cards.json",
  ha: "ha_hardware.json",
  hb: "hb_health_and_beauty.json",
  hg: "hg_home_and_garden.json",
  lb: "lb_luggage_and_bags.json",
  ma: "ma_mature.json",
  me: "me_media.json",
  na: "na_uncategorized.json",
  os: "os_office_supplies.json",
  pa: "pa_product_add_ons.json",
  rc: "rc_religious_and_ceremonial.json",
  se: "se_services.json",
  sg: "sg_sporting_goods.json",
  so: "so_software.json",
  tg: "tg_toys_and_games.json",
  vp: "vp_vehicles_and_parts.json",
};

// ---------------------------------------------------------------------------
// Stop words
// ---------------------------------------------------------------------------

const STOP_WORDS = new Set([
  "a",
  "an",
  "and",
  "by",
  "for",
  "from",
  "in",
  "of",
  "on",
  "or",
  "the",
  "to",
  "with",
  "other",
  "others",
  "not",
  "elsewhere",
  "classified",
  "general",
  "misc",
  "miscellaneous",
  "unspecified",
]);

// ---------------------------------------------------------------------------
// Token extraction & scoring (same as v2)
// ---------------------------------------------------------------------------

function tokenize(text: string): Set<string> {
  const tokens = new Set<string>();
  const parts = text.toLowerCase().split(TOKENIZE_RE);
  for (const part of parts) {
    const trimmed = part.trim();
    if (trimmed.length >= 2 && !STOP_WORDS.has(trimmed)) {
      tokens.add(trimmed);
    }
  }
  return tokens;
}

function extractBatchTokens(fullnames: string[]): Set<string> {
  const all = new Set<string>();
  for (const name of fullnames) {
    for (const token of tokenize(name)) {
      all.add(token);
    }
  }
  return all;
}

function scoreAndFilter(
  searchTokens: Set<string>,
  shopifyFullnames: string[],
  maxTargets: number
): string[] {
  const scored: { fullName: string; score: number }[] = [];
  for (const fullName of shopifyFullnames) {
    const targetTokens = tokenize(fullName);
    let overlap = 0;
    for (const token of targetTokens) {
      if (searchTokens.has(token)) {
        overlap++;
      }
    }
    if (overlap > 0) {
      scored.push({ fullName, score: overlap / targetTokens.size });
    }
  }
  scored.sort(
    (a, b) => b.score - a.score || a.fullName.localeCompare(b.fullName)
  );
  return scored.slice(0, maxTargets).map((s) => s.fullName);
}

// ---------------------------------------------------------------------------
// Shopify data loaders
// ---------------------------------------------------------------------------

async function loadAllShopifyLeafFullnames(): Promise<string[]> {
  const all: string[] = [];
  for (const filename of Object.values(SHOPIFY_FILES)) {
    const content = await readFile(join(SHOPIFY_DIR, filename), "utf-8");
    const data = JSON.parse(content) as { categories: ShopifyCategory[] };
    for (const c of data.categories) {
      if (c.children.length === 0) {
        all.push(c.full_name);
      }
    }
  }
  return all;
}

async function buildShopifyFullnameToId(): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  for (const filename of Object.values(SHOPIFY_FILES)) {
    const content = await readFile(join(SHOPIFY_DIR, filename), "utf-8");
    const data = JSON.parse(content) as { categories: ShopifyCategory[] };
    for (const c of data.categories) {
      map.set(c.full_name, c.id);
    }
  }
  return map;
}

// ---------------------------------------------------------------------------
// AI calls
// ---------------------------------------------------------------------------

async function generateSynonyms(
  client: OpenAI,
  ebayFullnames: string[]
): Promise<Set<string>> {
  const response = await client.chat.completions.create({
    model: MODEL,
    max_tokens: 4096,
    messages: [
      {
        role: "user",
        content: `For each eBay category below, list 3-5 synonyms or closely related terms that could help find the equivalent category in a different taxonomy (like Shopify). Focus on alternative names, related product types, and industry terms.

Categories:
${ebayFullnames.join("\n")}

Rules:
- Return a flat JSON array of unique keyword strings (lowercase)
- Include synonyms, alternative product names, and related industry terms
- Do NOT include the original category words — only NEW related terms
- Output ONLY the JSON array, no other text

JSON array of keyword strings:`,
      },
    ],
  });

  const { prompt_tokens, completion_tokens, total_tokens } =
    response.usage ?? {};
  process.stdout.write(
    ` [synonyms: ${prompt_tokens ?? "?"}in + ${completion_tokens ?? "?"}out = ${total_tokens ?? "?"}]`
  );

  const text = response.choices[0]?.message.content ?? "";
  const jsonMatch = text.match(JSON_ARRAY_RE);
  if (!jsonMatch) {
    console.warn("  Failed to parse synonym response");
    return new Set<string>();
  }

  const keywords = JSON.parse(jsonMatch[0]) as string[];
  return new Set(keywords.map((k) => k.toLowerCase().trim()));
}

async function mapBatch(
  client: OpenAI,
  sourceBatch: string[],
  filteredTargets: string[]
): Promise<Map<string, { target: string; confidence: number }>> {
  const sourceSet = new Set(sourceBatch);

  const numberedTargets = filteredTargets
    .map((name, i) => `${i + 1}. ${name}`)
    .join("\n");

  const response = await client.chat.completions.create({
    model: MODEL,
    max_tokens: 8192,
    messages: [
      {
        role: "user",
        content: `Map each source eBay category to the best matching Shopify target category.

SOURCE CATEGORIES (eBay — copy these strings verbatim into the "source" field):
${sourceBatch.join("\n")}

TARGET CATEGORIES (Shopify — identified by number):
${numberedTargets}

Rules:
- "source" MUST be an exact copy of a string from SOURCE CATEGORIES
- "targetIndex" MUST be the integer number (1-based) from TARGET CATEGORIES
- Do NOT return a target string — return the number only
- Match by semantic meaning: "Antiques > Furniture > Chairs" → a Furniture target
- Prefer more-specific (deeper) target categories when available
- If no good match exists, use the most appropriate top-level target with confidence < 0.5
- Output ONLY the JSON array, no other text

JSON array of { "source": "...", "targetIndex": <number>, "confidence": 0.0-1.0 }:`,
      },
    ],
  });

  const { prompt_tokens, completion_tokens, total_tokens } =
    response.usage ?? {};
  process.stdout.write(
    ` [tokens: ${prompt_tokens ?? "?"}in + ${completion_tokens ?? "?"}out = ${total_tokens ?? "?"}]`
  );

  const text = response.choices[0]?.message.content ?? "";
  const jsonMatch = text.match(JSON_ARRAY_RE);
  if (!jsonMatch) {
    console.error("  Failed to parse batch response:", text.slice(0, 200));
    return new Map();
  }

  const parsed = JSON.parse(jsonMatch[0]) as Array<{
    confidence: number;
    source: string;
    targetIndex: number;
  }>;

  const results = new Map<string, { target: string; confidence: number }>();

  for (const entry of parsed) {
    if (!sourceSet.has(entry.source)) {
      continue;
    }
    const idx = entry.targetIndex - 1;
    if (idx < 0 || idx >= filteredTargets.length) {
      console.warn(
        `  Invalid targetIndex ${entry.targetIndex} for "${entry.source.slice(0, 50)}"`
      );
      continue;
    }
    const target = filteredTargets[idx];
    if (target === undefined) {
      continue;
    }
    results.set(entry.source, {
      target,
      confidence: entry.confidence,
    });
  }

  return results;
}

// ---------------------------------------------------------------------------
// eBay version resolver
// ---------------------------------------------------------------------------

async function resolveEbayVersion(): Promise<string> {
  const entries = await readdir(EBAY_INTEGRATIONS_DIR);
  const versions = entries
    .filter((f) => !(f.startsWith(".") || f.endsWith(".json")))
    .sort();
  const latest = versions.at(-1);
  if (!latest) {
    throw new Error("No eBay version directories found");
  }
  return latest;
}

// ---------------------------------------------------------------------------
// Consolidation
// ---------------------------------------------------------------------------

async function consolidate(
  perCategoryDir: string,
  finalPath: string
): Promise<void> {
  const files = (await readdir(perCategoryDir)).filter((f) =>
    f.endsWith(".json")
  );
  const flat: Record<string, string> = {};
  for (const file of files) {
    const content = await readFile(join(perCategoryDir, file), "utf-8");
    const data = JSON.parse(content) as { mappings: MappingEntry[] };
    for (const m of data.mappings) {
      if (m.mappingSource !== "unmapped" && m.mappingSource !== "skipped") {
        flat[m.ebayId] = m.shopifyCategoryId;
      }
    }
  }
  await writeFile(finalPath, JSON.stringify(flat, null, 2));
  console.log(
    `\nConsolidated ${Object.keys(flat).length} mappings -> ${finalPath}`
  );
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error("Set OPENAI_API_KEY in packages/taxonomy/scripts/.env");
  process.exit(1);
}

const args = process.argv.slice(2);
const categoryFilter = args.includes("--category")
  ? args[args.indexOf("--category") + 1]
  : null;
const dryRun = args.includes("--dry-run");
const maxTargetsArg = args.includes("--max-targets")
  ? Number.parseInt(args[args.indexOf("--max-targets") + 1] ?? "", 10)
  : Number.NaN;
const maxTargets = Number.isNaN(maxTargetsArg)
  ? DEFAULT_MAX_TARGETS
  : maxTargetsArg;

const client = new OpenAI({ apiKey });
const ebayVersion = await resolveEbayVersion();
const EBAY_MAPPINGS_DIR = join(EBAY_INTEGRATIONS_DIR, ebayVersion, "mappings");
const PER_CATEGORY_DIR = join(EBAY_MAPPINGS_DIR, "categories");
const LOW_CONFIDENCE_PATH = join(EBAY_MAPPINGS_DIR, "low-confidence.json");
const FINAL_MAPPING_PATH = join(EBAY_MAPPINGS_DIR, "mappings.json");

if (!existsSync(LOW_CONFIDENCE_PATH)) {
  console.error(`Not found: ${LOW_CONFIDENCE_PATH}`);
  console.error("Run extract-low-confidence.ts first.");
  process.exit(1);
}

console.log(`eBay version: ${ebayVersion}`);
console.log(`Max targets per batch: ${maxTargets}`);
console.log(`Model: ${MODEL}`);
if (dryRun) {
  console.log("DRY RUN — no AI calls will be made\n");
}

// Load inputs
const lowConfData = JSON.parse(
  await readFile(LOW_CONFIDENCE_PATH, "utf-8")
) as {
  entries: ReviewEntry[];
  stats: { categories: number; total: number; needsReview: number };
};

let entries = lowConfData.entries;
if (categoryFilter) {
  entries = entries.filter((e) => e.ebayCategory === categoryFilter);
  console.log(`Filtered to category: ${categoryFilter}`);
}

console.log(`\nEntries to retry: ${entries.length}`);

// Group by category for patching later
const byCategory = new Map<string, ReviewEntry[]>();
for (const entry of entries) {
  const existing = byCategory.get(entry.ebayCategory) ?? [];
  existing.push(entry);
  byCategory.set(entry.ebayCategory, existing);
}

console.log(`Across ${byCategory.size} categories\n`);

if (dryRun) {
  for (const [cat, catEntries] of byCategory) {
    console.log(`  ${cat}: ${catEntries.length} entries`);
  }
  console.log("\nDry run complete.");
  process.exit(0);
}

// Load Shopify data
console.log("Loading Shopify data...");
const allShopifyFullnames = await loadAllShopifyLeafFullnames();
const shopifyFNtoId = await buildShopifyFullnameToId();
console.log(`  ${allShopifyFullnames.length} Shopify leaf categories\n`);

// Temp log directory
const TEMP_DIR = join(import.meta.dir, "../temp/retry-logs");
await mkdir(TEMP_DIR, { recursive: true });

// Separate excluded entries (test/internal) from retryable entries
const excluded = entries.filter((e) => isExcludedCategory(e.ebayFullName));
const retryable = entries.filter((e) => !isExcludedCategory(e.ebayFullName));

if (excluded.length > 0) {
  console.log(
    `Excluded ${excluded.length} test/internal categories (auto-uncategorized)`
  );
}
console.log(`Retryable entries: ${retryable.length}\n`);

// Build original confidence lookup for comparison
const originalConfidenceMap = new Map<string, number>();
for (const entry of retryable) {
  originalConfidenceMap.set(entry.ebayFullName, entry.confidence);
}

// Process retryable entries in batches (concurrent)
const CONCURRENCY = 3;
const allFullnames = retryable.map((e) => e.ebayFullName);
const improvements = new Map<
  string,
  { target: string; confidence: number; shopifyId: string }
>();
const totalBatches = Math.ceil(allFullnames.length / BATCH_SIZE);

// Build batch list
const batches: { batch: string[]; batchNum: number }[] = [];
for (let i = 0; i < allFullnames.length; i += BATCH_SIZE) {
  batches.push({
    batch: allFullnames.slice(i, i + BATCH_SIZE),
    batchNum: Math.floor(i / BATCH_SIZE) + 1,
  });
}

async function processBatch(item: {
  batch: string[];
  batchNum: number;
}): Promise<void> {
  const { batch, batchNum } = item;

  process.stdout.write(`Batch ${batchNum}/${totalBatches}: synonyms...`);

  // Step 1: Generate synonyms
  const synonyms = await generateSynonyms(client, batch);

  // Step 2: Score with expanded tokens
  const originalTokens = extractBatchTokens(batch);
  const expandedTokens = new Set([...originalTokens, ...synonyms]);
  const filteredTargets = scoreAndFilter(
    expandedTokens,
    allShopifyFullnames,
    maxTargets
  );

  process.stdout.write(` (${filteredTargets.length} targets) mapping...`);

  // Step 3: AI mapping
  const results = await mapBatch(client, batch, filteredTargets);

  let improved = 0;
  for (const [source, result] of results) {
    const shopifyId = shopifyFNtoId.get(result.target) ?? "na";
    const original = originalConfidenceMap.get(source) ?? 0;
    // Only accept if confidence actually improved over the original
    if (result.confidence > original) {
      improvements.set(source, { ...result, shopifyId });
      improved++;
    }
  }

  // Write batch log for inspection
  const batchLog = {
    batchNum,
    sources: batch,
    originalTokens: [...originalTokens].sort(),
    synonyms: [...synonyms].sort(),
    expandedTokens: [...expandedTokens].sort(),
    filteredTargets,
    results: Object.fromEntries(results),
    improvements: Object.fromEntries(
      [...improvements].filter(([k]) => batch.includes(k))
    ),
  };
  await writeFile(
    join(TEMP_DIR, `batch-${String(batchNum).padStart(3, "0")}.json`),
    JSON.stringify(batchLog, null, 2)
  );

  process.stdout.write(` ${improved}/${batch.length} improved\n`);
}

// Run with concurrency
let batchIdx = 0;
async function worker(): Promise<void> {
  while (batchIdx < batches.length) {
    const item = batches[batchIdx++];
    if (item !== undefined) {
      await processBatch(item);
    }
  }
}

console.log(
  `Processing ${totalBatches} batches (concurrency: ${CONCURRENCY})...\n`
);
await Promise.all(
  Array.from({ length: Math.min(CONCURRENCY, batches.length) }, () => worker())
);

console.log(`\nTotal improvements: ${improvements.size}/${retryable.length}`);
console.log(`Excluded (test/internal): ${excluded.length}`);

// Build a set of excluded fullnames for patching
const excludedFullnames = new Set(excluded.map((e) => e.ebayFullName));

// Patch per-category files
if (improvements.size === 0 && excluded.length === 0) {
  console.log("No improvements found. Files unchanged.");
  process.exit(0);
}

console.log("\nPatching category files...");

// Resolve slug mapping by checking which files actually exist
const categoryFiles = (await readdir(PER_CATEGORY_DIR)).filter((f) =>
  f.endsWith(".json")
);
const slugToFile = new Map<string, string>();
for (const file of categoryFiles) {
  const content = await readFile(join(PER_CATEGORY_DIR, file), "utf-8");
  const data = JSON.parse(content) as CategoryFile;
  slugToFile.set(data.ebayCategory, file);
}

let patchedFiles = 0;
let patchedEntries = 0;

for (const [category] of byCategory) {
  const file = slugToFile.get(category);
  if (!file) {
    console.warn(`  Warning: no mapping file found for "${category}"`);
    continue;
  }

  const filePath = join(PER_CATEGORY_DIR, file);
  const data = JSON.parse(await readFile(filePath, "utf-8")) as CategoryFile;

  let changed = 0;
  for (const mapping of data.mappings) {
    // Mark test/internal categories as uncategorized
    if (excludedFullnames.has(mapping.ebayFullName)) {
      mapping.shopifyCategoryId = "na";
      mapping.shopifyFullName = "Uncategorized";
      mapping.confidence = 0;
      mapping.mappingSource = "excluded";
      changed++;
      continue;
    }
    const improvement = improvements.get(mapping.ebayFullName);
    if (improvement) {
      mapping.shopifyCategoryId = improvement.shopifyId;
      mapping.shopifyFullName = improvement.target;
      mapping.confidence = improvement.confidence;
      mapping.mappingSource = `${MODEL}-retry`;
      changed++;
    }
  }

  if (changed > 0) {
    // Recalculate stats
    data.highConfidence = data.mappings.filter(
      (m) => m.confidence >= 0.7
    ).length;
    data.lowConfidence = data.mappings.filter(
      (m) => m.confidence < 0.5 && m.mappingSource !== "skipped"
    ).length;

    await writeFile(filePath, JSON.stringify(data, null, 2));
    console.log(`  ${category}: ${changed} entries updated`);
    patchedFiles++;
    patchedEntries += changed;
  }
}

console.log(`\nPatched ${patchedEntries} entries across ${patchedFiles} files`);

// Reconsolidate
await consolidate(PER_CATEGORY_DIR, FINAL_MAPPING_PATH);

// Re-run low-confidence extraction to update the report
console.log("\nDone. Run extract-low-confidence.ts to see updated stats.");
